### PR TITLE
Added "Restart" to actions

### PR DESCRIPTION
**Pull request by Whomiga**
Added the "Restart" option to the actions available - everything else should be unchanged

### CODE REVIEW

**Comment by Whomiga** [comment]
Apparently, to send a POST indicating a button press, the nonce has to be retrieved from the page that the button is on in order to securely handle the POST.

**Comment by edgan** [comment]
Yeah, I figured out the nonce while doing my own research. I also reused my existing method to retrieve it with some tweaking.

I have implemented your method. You implemented how I would have implemented it. I should have a new release today.

**Comment by edgan** [comment]
I am going to add an "Are you sure?" question for it, and also allow a automatic yes to the question.

**Comment by Whomiga** [comment]
> I am going to add an "Are you sure?" question for it, and also allow a automatic yes to the question.

I made a modified version that only has the login and restart parts, coded my IP and Password into it, but allows for those to be changed for my own use as I just needed the restart functionality (and didn't need all the rest) as it was being automatically called by a program I've made to detect the loss of internet connection,

**Comment by Whomiga** [comment]
> Yeah, I figured out the nonce while doing my own research. I also reused my existing method to retrieve it with some tweaking.
> 
> I have implemented your method. You implemented how I would have implemented it. I should have a new release today.

I tried to follow your style as much as I could

**Comment by edgan** [comment]
> I tried to follow your style as much as I could

Yeah, I could tell. But you also deleted all the other functions, and I had added even more stuff after your fork.

I just finished testing my question code. Time to make a new release.

**Comment by edgan** [comment]
Thank you for the code, and the idea. :)

**Comment by Whomiga** [comment]
> > I tried to follow your style as much as I could
> 
> Yeah, I could tell. But you also deleted all the other functions, and I had added even more stuff after your fork.
> 
> I just finished testing my question code. Time to make a new release.

The latest fork I made after your latest stuff and just added the extra code - the fork is yours plus my extras (Or it should be)

**Comment by edgan** [comment]
I am adding a THANKS.md in the next release to share my thanks.

**Pull request closed without merging**
